-- CreateTable
CREATE TABLE "Cliente" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "nome_cliente" TEXT NOT NULL,
    "nome_entrega" TEXT NOT NULL,
    "data_entrega" DATETIME NOT NULL,
    "logradouro" TEXT NOT NULL,
    "numero" TEXT NOT NULL,
    "bairro" TEXT NOT NULL,
    "cep" TEXT NOT NULL,
    "cidade" TEXT NOT NULL,
    "ponto_referencia" TEXT,
    "obs" TEXT,
    "email" TEXT NOT NULL,
    "telefone_1" TEXT NOT NULL,
    "telefone_2" TEXT,
    "nome_produto_1" TEXT NOT NULL,
    "nome_produto_2" TEXT,
    "nome_produto_3" TEXT,
    "nome_produto_4" TEXT,
    "nome_produto_5" TEXT,
    "desc_produto_1" TEXT NOT NULL,
    "desc_produto_2" TEXT,
    "desc_produto_3" TEXT,
    "desc_produto_4" TEXT,
    "desc_produto_5" TEXT,
    "qtd_1" INTEGER NOT NULL,
    "qtd_2" INTEGER,
    "qtd_3" INTEGER,
    "qtd_4" INTEGER,
    "qtd_5" INTEGER,
    "forma_pagamento" TEXT NOT NULL,
    "numero_parcelas" INTEGER NOT NULL,
    "cpf" TEXT NOT NULL,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL
);
